# 通知服务部署配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: ecommerce-k8s
  labels:
    app: notification-service
    tier: backend
    component: microservice
    service: notification
spec:
  replicas: 1  # 通知服务通常只需要1个副本
  selector:
    matchLabels:
      app: notification-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0  # 确保至少有一个副本运行
      maxSurge: 1
  template:
    metadata:
      labels:
        app: notification-service
        tier: backend
        component: microservice
        service: notification
        version: v1.0
    spec:
      containers:
      - name: notification-service
        image: ecommerce-basic-notification-service:latest
        imagePullPolicy: Never  # 使用本地镜像
        ports:
        - containerPort: 5004
          name: http
          protocol: TCP
        env:
        # 数据库配置
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: notification_database_url
        # Redis配置
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: redis_notification_url
        # RabbitMQ配置
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: rabbitmq_url
        # 应用配置
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: flask_env
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: log_level
        # 密钥配置
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt_secret
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: api_key
        # 邮件配置
        - name: SMTP_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: smtp_host
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: smtp_port
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: smtp_username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: smtp_password
        # 服务间通信
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: user_service_url
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: product_service_url
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: order_service_url
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5004
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5004
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 5004
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: app-logs
          mountPath: /var/log/app
        - name: templates
          mountPath: /var/templates
      volumes:
      - name: app-logs
        emptyDir: {}
      - name: templates
        persistentVolumeClaim:
          claimName: templates-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: ecommerce-k8s
  labels:
    app: notification-service
    tier: backend
    service: notification
spec:
  selector:
    app: notification-service
  ports:
  - name: http
    port: 80
    targetPort: 5004
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None
---
# 通知服务HPA配置（水平自动扩缩容）
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service-hpa
  namespace: ecommerce-k8s
  labels:
    app: notification-service
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max
---
# 通知服务PodDisruptionBudget配置（Pod中断预算）
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-service-pdb
  namespace: ecommerce-k8s
  labels:
    app: notification-service
    tier: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: notification-service
---
# 通知服务网络策略（可选）
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: notification-service-netpol
  namespace: ecommerce-k8s
  labels:
    app: notification-service
    tier: backend
spec:
  podSelector:
    matchLabels:
      app: notification-service
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api-gateway
    - podSelector:
        matchLabels:
          tier: backend
    ports:
    - protocol: TCP
      port: 5004
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: postgres
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - podSelector:
        matchLabels:
          app: rabbitmq
    ports:
    - protocol: TCP
      port: 5672
  - to:
    - podSelector:
        matchLabels:
          tier: backend
    ports:
    - protocol: TCP
      port: 80
  # 允许SMTP出站连接
  - to: []
    ports:
    - protocol: TCP
      port: 587
    - protocol: TCP
      port: 465
    - protocol: TCP
      port: 25
  # 允许DNS查询
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
